const COLLECTIONS = {
  PRIMARY: {
    DATA_LIST: "data_list",
    USERS: "users",
    FLOW_METADATA: "flow_metadata",
    ACTION_HISTORY: "action_history",
    FIELD_MASTER: "field_master",
    INSTANCES: "instances",
    ACTIVE_TASKS: "active_tasks",
    FIELD_METADATA: "field_metadata",
    ACTIVE_TASK_DETAILS: "active_task_details",
    TASK_LOG: "task_log",
    DATA_ACCESS_LOG: "data_access_log",
    TASK_OWNER_LOG: "task_owner_log",
    FLOW_STEPS: "flow_steps",
    AUTO_SEQUENCE: "auto_sequence",
    DASHBOARD_METADATA: "dashboard_metadata",
    DASHBOARD_PAGES: "dashboard_pages",
    DASHBOARD_COMPONENTS: "dashboard_components",
    RULE_METADATA: "rule_metadata",
    TRIGGER_METADATA: "trigger_metadata",
    DOCUMENT_METADATA: "document_metadata",
    RECURSIVE_JOBS: "recursive_jobs",
    ENTITY_TECHNICAL_DETAILS: "entity_technical_details",
    CUSTOM_SEQUENCE: "custom_sequence",
    SYSTEM_EVENT_TRIGGER: "system_event_trigger",
    DATA_EXTRACTION: "data_extraction",
    SCHEDULER_LOG: "scheduler_log",
    TASK_METADATA: "task_metadata",
    FLOW_TRACKER: "flow_tracker",
    AGGREGATE_REPORT_METADATA: "aggregate_report_metadata",
  },
  WORKHALL_DOCUMENT_ENGINE: {
    DOCUMENT_LOG: "document_log",
  },
  SCHEDULER: {
    SCHEDULER_AUDIT: "scheduler_audit",
    RECURSIVE_JOBS: "recursive_jobs",
  },
};

export { COLLECTIONS };
